BboardSite/BboardSite/urls.py
from django.contrib import admin
from django.urls import path, include
from BboardSite import settings
from django.conf.urls.static import static
from django.conf import settings
from bboard.views import page_not_found
from django.contrib.auth import views as auth_views
from bboard.views import index, about

urlpatterns = [
    path('', index, name='index'),
    path('bboard/', include('bboard.urls')),
    path('admin/', admin.site.urls),
    path('about/', about, name='about'),
    path('users/', include('users.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BboardSite/bboard/urls.py
from django.urls import path
from .views import (
    index, about, user_info, add_addd, edit_addd,
 delete_addd, search_addd, filter_addd, user_addd, read_addd, contact
)

app_name = 'bboard'

urlpatterns = [
    path('', index, name='index'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('user-info/<int:user_id>/', user_info, name='user_info'),
    path('addd/add/', add_addd, name='add_addd'),
    # path('addd/<int:addd_id>/', detail_addd, name='addd_detail'),
    path('addd/edit/<slug:slug>/', edit_addd, name='addd_edit'),
    path('addd/delete/<int:addd_id>/', delete_addd, name='addd_delete'),
    path('user-info/<int:user_id>/', user_addd, name='user_addd'),
    path('addd/<slug:slug>/', read_addd, name='read_addd'),
    # path('addd/edit/<slug:slug>/', update_addd, name='update_addd'),
    path('search/', search_addd, name='search_addd'),
    path('filter/', filter_addd, name='filter_addd'),
]

BboardSite/users/urls.py
from django.urls import path
from .views import register, log_in, log_out, user_profile, change_password, registration_done


app_name = 'users'
urlpatterns = [
    path('registration/done/', registration_done, name='registration_done'),
    path('registration/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('profile/<int:pk>/', user_profile, name='profile'),
    path('change-password', change_password, name='change-password'),
]

BboardSite/bboard/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from slugify import slugify

class Addd(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор', related_name='Addds')
    title = models.CharField(max_length=100, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Описание')
    image = models.ImageField(upload_to='Addds/', blank=True, null=True, verbose_name='Изображение')
    created_at = models.DateTimeField(default=timezone.now, verbose_name='Дата создания', editable=False)
    brand = models.CharField(max_length=100, verbose_name="Марка")
    model = models.CharField(max_length=100, verbose_name="Модель")
    year = models.PositiveIntegerField(verbose_name="Год выпуска")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена', default=0)
    slug = models.SlugField(max_length=200, unique=True, editable=False, null=True)
    
    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return self.title


  

    def get_absolute_url(self):
        return reverse('bboard:read_addd', kwargs={'slug': self.slug})


    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'
        ordering = ['-created_at']

BboardSite/bboard/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Addd


# class PostForm(forms.Form):
#     title = forms.CharField(max_length=200, label='Заголовок')
#     text = forms.CharField(widget=forms.Textarea, label='Текст поста')
#     author = forms.ModelChoiceField(queryset=User.objects.all(), label='Автор')
#     image = forms.ImageField(required=False, label='Изображение')

class AdddForm(forms.ModelForm):
    # Дополняем конструктор родительского класса
    # def __init__(self, *args, **kwargs):
    #     # получаем author из именованных вргументов (его передали во views)
    #     author = kwargs.pop('author', None)
    #     # вызывем конгструктор родительского класса
    #     super(AdddForm, self).__init__(*args, **kwargs)
    #     #устанавливаем начальное значение поля author
    #     self.fields['author'].initial = author
    #     # отключаем видимость этого поля в форме
    #     self.fields['author'].disabled = True
    #     self.fields['author'].widget = forms.HiddenInput()


    class Meta:
        model = Addd
        fields = [ 'title', 'content', 'image', 'brand', 'model', 'year', 'price']
        
        labels = {
        'title': 'Заголовок',
        'content': 'Описание',
        'image': 'Изображение',
        'price': 'Цена',
        'brand': 'Марка',
        'model': 'Модель',
        'year': 'Год Выпуска'
        
    }

class FilterForm(forms.Form):
    author = forms.ModelChoiceField(queryset=User.objects.all(), label='Автор', required=False)
    created_at = forms.DateField(label='Дата публикации',
                                 widget=forms.DateInput(attrs={'type': 'date'}),
                                 input_formats=['%Y-%m-%d'],
                                 required=False)

    
    

BboardSite/bboard/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Addd
from .forms import AdddForm, FilterForm
from django.http import HttpResponseNotFound

def trigger_404(request):
    return HttpResponseNotFound(render(request, 'blog/404.html'))

def trigger_403(request):
    return HttpResponseNotFound(render(request, 'blog/403.html'))

def trigger_500(request):
    return HttpResponseNotFound(render(request, 'blog/500.html'))




def index(request):
    addds = Addd.objects.all().order_by('-created_at')
    count_addds = addds.count()
    per_page = 6
    paginator = Paginator(addds, per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    filter_form = FilterForm()
    context = {"title": "Главная страница", "page_obj": page_obj, "count_addds": count_addds, "filter_form": filter_form}
    return render(request, template_name='bboard/index.html', context=context)

def about(request):
    count_addds = Addd.objects.count()
    context = {"title": "О сайте", "count_addds": count_addds}
    return render(request, template_name='bboard/about.html', context=context)


def contact(request):
    count_addds = Addd.objects.count()
    context = {"title": "О сайте", "count_addds": count_addds}
    return render(request, template_name='bboard/contact.html', context=context)

@login_required
def add_addd(request):
    if request.method == "GET":
        addd_form = AdddForm()
        context = {'title': 'Добавить объявление', 'form': addd_form}
        return render(request, template_name='bboard/addd_add.html', context=context)
    if request.method == "POST":
        addd_form = AdddForm(data=request.POST, files=request.FILES)
        if addd_form.is_valid():
            addd = addd_form.save(commit=False)
            addd.author = request.user
            addd.save()
            return redirect('bboard:index')
        context = {'title': 'Добавить объявление', 'form': addd_form}
        return render(request, template_name='bboard/addd_add.html', context=context)

def read_addd(request, slug):
    addd = get_object_or_404(Addd, slug=slug)
    context = {"title": "Информация об объявлении", "addd": addd}
    return render(request, template_name='bboard/addd_detail.html', context=context)

# @login_required
# def update_addd(request, pk):
#     addd = get_object_or_404(Addd, pk=pk)
#     if request.method == "POST":
#         addd_form = AdddForm(data=request.POST, files=request.FILES, instance=addd)
#         if addd_form.is_valid():
#             addd = addd_form.save(commit=False)
#             addd.author = request.user
#             addd.save()
#             return redirect('bboard:read_addd', pk=addd.id)
#     else:
#         addd_form = AdddForm(instance=addd)
#     return render(request, template_name="bboard/addd_edit.html", context={"form": addd_form})

@login_required
def edit_addd(request, slug):
    addd = get_object_or_404(Addd, slug=slug)
    if request.method == "POST":
        addd_form = AdddForm(data=request.POST, files=request.FILES, instance=addd)
        if addd_form.is_valid():
            addd = addd_form.save(commit=False)
            addd.author = request.user
            addd.save()
            return redirect('bboard:read_addd', slug=addd.slug)
    else:
        addd_form = AdddForm(instance=addd)
    return render(request, template_name="bboard/addd_edit.html", context={"form": addd_form})

@login_required
def delete_addd(request, addd_id):
    addd = get_object_or_404(Addd, pk=addd_id, author=request.user)
    context = {"addd": addd}
    if request.method == "POST":
        addd.delete()
        return redirect('bboard:index')
    return render(request, template_name='bboard/addd_delete.html', context=context)

def page_not_found(request, exception):
    return render(request, template_name="bboard/404.html", context={"title": "404"})

def forbidden(request, exception):
    return render(request, template_name="bboard/403.html", context={"title": "403"})

def server_error(request):
    return render(request, template_name="bboard/500.html", context={"title": "500"})

def user_addd(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    addd = Addd.objects.filter(author=user).select_related('author')
    context = {'user': user, 'addd': addd}
    return render(request, template_name='bboard/user_addd.html', context=context)

@login_required
def user_info(request, user_id):
    user = get_object_or_404(User, pk=user_id)
    addds = Addd.objects.filter(author=user).select_related('author')
    context = {'user': user, 'addds': addds}
    return render(request, template_name='bboard/user_info.html', context=context)

def search_addd(request):
    query = request.GET.get('query')
    query_text = Q(title__icontains=query) | Q(content__icontains=query)
    results = Addd.objects.filter(query_text)
    per_page = 6
    paginator = Paginator(results, per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    count_addds = results.count()
    context = {"title": "Главная страница", "page_obj": page_obj, "count_addds": count_addds}
    return render(request, template_name='bboard/index.html', context=context)

def filter_addd(request):
    author_id = request.GET.get('author')
    if not author_id:
        results = Addd.objects.all()
    else:
        author = User.objects.get(pk=author_id)
        query_text = Q(author__exact=author)
        results = Addd.objects.filter(query_text)
    per_page = 6
    paginator = Paginator(results, per_page)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
    count_addds = results.count()
    filter_form = FilterForm()
    context = {"title": "Главная страница", "page_obj": page_obj, "count_addds": count_addds, "filter_form": filter_form}
    return render(request, template_name='bboard/index.html', context=context)

BboardSite/bboard/templates/bboard/about.html
{% extends 'bboard/base.html' %}

{% block content %}
<div class="container">
    <h1>О нашем сайте HotMotors</h1>
    <p>Потому что мы — не просто доска объявлений. Мы — сообщество байкеров, коллекционеров и просто людей, влюблённых в свободу двух колёс.
        Будь то первый мотоцикл или уже десятый — здесь ты найдёшь именно то, что ищешь.</p>
    
    <h2>Что вы найдёте у нас:</h2>
    <ul> HotMotors </li>
        <li>Идеи для прогулок и путешествий с питомцем</li>
        <li>Теплую атмосферу и добрые фотографии</li>
        <li>Возможность поделиться своей историей</li>
        <li>Сообщество людей, которые любят собак так же сильно, как и вы</li>
    </ul>
    <p>Спасибо, что зашли!</p>
</div>
{% endblock %}

BboardSite/bboard/templates/bboard/addd_add.html
{% extends 'bboard/base.html' %}

{% block content %}
<div class="ads_add">
<h2>Добавить новое объявление</h2>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="custom-button">Добавить объявление</button>
</form>
</div>
{% endblock content %}

BboardSite/bboard/templates/bboard/addd_delete.html
{% extends 'bboard/base.html' %}
{% load static %}

{% block content %}
<div class="delet-list">
    <h3>Удаление объявления</h3>
    <p>Автор - {{ addd.author }}</p>
    <p>Заголовок - {{ addd.title }}</p>
    <form method="post">
        {% csrf_token %}
        {% if addd.image %}
        <img src="{{ addd.image.url }}" width="200px" height="auto">
    {% else %}
        <img src="{% static 'img/no_image.jpg' %}" width="200px" height="auto">
    {% endif %}
        <button type="submit" class="custom-button">Удалить объявление</button>
        <a href="{% url 'bboard:index' %}">
            <button type="button" class="custom-button">Отменить</button>
        </a>
    </form>
</div>
{% endblock content %}

BboardSite/bboard/templates/bboard/addd_detail.html
{% extends 'bboard/base.html' %}
{% load static %}

{% block content %}
<div class="update-list">
    <h2>Информация о объявление № {{ addd.pk }}</h2>
    {% if user.is_authenticated %}
    <a href="{% url 'bboard:user_info' user_id=addd.author.id %}">
        <b>{{ addd.author }}</b>
    </a>
    {% else %}
        <b>{{ addd.author }}</b>
    {% endif %}
    <hr>
    <h3>{{ addd.title }}</h3>
    {% if addd.image %}
        <img src="{{ addd.image.url }}" width="200px" height="auto">
    {% else %}
        <img src="{% static 'img/no_image.jpg' %}" width="200px" height="auto">
        <p>{{ addd.content }}</p>
    {% endif %}
    <p>{{ addd.content }}</p>
    <br>    
    <p>{{ addd.text }}</p>
    <p>{{ addd.created_at }}</p>
    {% if user == addd.author %}
    <div class='btn-actions'>
        <div class='btn-edit-post'>
            <a href="{% url 'bboard:addd_edit' slug=addd.slug %}">
                <button type="button" class="custom-button">Редактировать</button>
            </a>
        </div>
        <div class='btn-del-post'>
            <a href="{% url 'bboard:addd_delete' addd_id=addd.id %}">
                <button type="button" class="custom-button">Удалить</button>
            </a>
        </div>
    </div>
    {% elif user.is_superuser %}
    <div class='btn-actions'>
        <div class='btn-del-post'>
            <a href="{% url 'bboard:addd_delete' addd_id=addd.id %}">
                <button type="button" class="custom-button">Удалить</button>
            </a>
        </div>
    </div>
    {% endif %}
</div>
{% endblock content %}

BboardSite/bboard/templates/bboard/addd_edit.html
{% extends 'bboard/base.html' %}

{% block content %}
<div class="edit-list">
<h2>Редактировать объявление</h2>
<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="custom-button">Изменить объявление</button>
</form>
</div>

{% endblock content %}

BboardSite/bboard/templates/bboard/addd_update.html
{% extends 'bboard/base.html' %}

{% block content %}
<div class="redact-list">
  <h2>Редактировать объявление</h2>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="custom-button">Сохранить изменения</button>
  </form>
</div>
{% endblock %}

BboardSite/bboard/templates/bboard/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <title>{{title}}</title>
</head>
<body>
    <header>
        <div class="header-content">
            <h3 class="site-title"><a href="/">HotMotors</a></h3>
            <nav>
                <div class="menu">
                    <div><a href="{% url 'bboard:index' %}">Главная</a></div>
                    {% if not user.is_authenticated %}
                        <div><a href="{% url 'users:login' %}">Войти</a></div>
                        <div><a href="{% url 'users:register' %}">Зарегистрироваться</a></div>
                    {% else %}
                        <div><a href="{% url 'users:profile' pk=user.pk %}">{{user.username}}</a></div>
                        <div><a href="{% url 'users:logout' %}">Выход</a></div>
                    {% endif %}
                    <div class="menu-divider">|</div>
                    <div><a href="{% url 'bboard:add_addd' %}">Новое объявление</a></div>
                    <div><a href="{% url 'bboard:about' %}">О сайте</a></div>
                    <div><a href="{% url 'bboard:contact' %}">Контакты</a></div>
                </div>
            </nav>
        </div>
    </header>
    {% if messages %}
        {% for message in messages %}
            <div class="message">{{ message }}</div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock content %}

    <div class="footer-bottom">
        <p>&copy; 2024 сайт объявлений  про мотоциклы. Все права защищены.</p>
    </div>
</body>
</html>

BboardSite/bboard/templates/bboard/contact.html
{% extends 'bboard/base.html' %}
{% load static %}

{% block content %}
<div class="contacts-container">
    <h2>Контакты</h2>
    <p>Если у вас возникли вопросы или предложения — свяжитесь с нами:</p>
    
    <p><strong>Телефон:</strong> +7 (495) 123‑45‑67</p>
    <p><strong>Доп. номер:</strong> +7 (901) 765‑43‑21</p>
</div>
{% endblock %}

BboardSite/bboard/templates/bboard/index.html
{% extends 'bboard/base.html' %}
{% load static %}
{% load custom_tags %}
{% comment %} {% block content %}
    <form action="{% url 'bboard:search_addd' %}" method="get">
        <input type="search" name="query">
        <button type="submit" class="search-button">Поиск</button>
    </form>
    <form action="{% url 'bboard:filter_addd' %}" method="get">
        {{filter_form.as_p}}
        <button type="submit" class="filter-button">Фильтровать</button>
    </form>
    <h2>{{post_text}}</h2>
    {% if page_obj|length == 0 %}
        <h3>По вашему запросу ничего не найдено!</h3>
    {% else %}
        <div class="post-list">
            {% for post in page_obj %}
                <div class="post-item">
                    <div>
                        <a href="{% url 'bboard:user_addd' user_id=post.author.pk %}">
                            <h3><b>{{ post.author }}</b></h3>
                        </a>
                    </div>
                    {% if post.image %}
                        <img src="{{post.image.url}}" width="150px" height="auto">
                    {% else %}
                        <img src="{% static 'img/no_image.jpg' %}" width="150px" height="auto">
                    {% endif %}
                    <h4><a href="{{post.get_absolute_url}}">{{ post.title }}</a></h4>
                    <p>{{ post.text }}</p>
                    <p><strong>Марка:</strong> {{ post.brand }}</p>
                    <p><strong>Модель:</strong> {{ post.model }}</p>
                    <p><strong>Год выпуска:</strong> {{ post.year }}</p>
                    <p><strong>Цена:</strong> {{ post.price }} ₽</p>
                    <p>{{ post.created_at }}</p>
                </div>
            {% endfor %}
        </div>
        <div class="pagination">
            <div class="step-links">
                <form method="get" style="display: inline;">
                    {% if page_obj.has_previous %}
                        <button type="submit" name="page" value="1">&laquo; Первая</button>
                        <button type="submit" name="page" value="{{ page_obj.previous_page_number }}">Предыдущая</button>
                    {% endif %}
                    <span class="current">
                        Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                    </span>
                    {% if page_obj.has_next %}
                        <button type="submit" name="page" value="{{ page_obj.next_page_number }}">Следующая</button>
                        <button type="submit" name="page" value="{{ page_obj.paginator.num_pages }}">Последняя &raquo;</button>
                    {% endif %}
                </form>
            </div>
        </div>
    {% endif %}
{% endblock content %}  {% endcomment %}



{% comment %} {% extends 'bboard/base.html' %}
{% load static %}
{% load custom_tags %} {% endcomment %}

{% block content %}
<div class="search_list">
    <form action="{% url 'bboard:search_addd' %}" method="get">
        <input type="search" name="query">
        <button type="submit" class="search-button">Поиск</button>
    </form>
    <form action="{% url 'bboard:filter_addd' %}" method="get">
        {{ filter_form.as_p }}
        <button type="submit" class="filter-button">Фильтровать</button>
    </form>
</div>
    
    <h2>{{ post_text }}</h2>
    
    {% if page_obj|length == 0 %}
        <h3>По вашему запросу ничего не найдено!</h3>
    {% else %}
        <div class="post-list">
            {% for addd in page_obj %}
                <div class="post-item">
                    <div>
                        <a href="{% url 'bboard:user_info' user_id=addd.author.id %}">
                            <h3><b>{{ addd.author }}</b></h3>
                        </a>
                    </div>
                    {% if addd.image %}
                        <img src="{{ addd.image.url }}" width="150px" height="auto">
                    {% else %}
                        <img src="{% static 'img/no_image.jpg' %}" width="150px" height="auto">
                    {% endif %}
                    <h4><a href="{{ addd.get_absolute_url }}">{{ addd.title }}</a></h4>
                    {% comment %} <p>{{ addd.content }}</p> {% endcomment %}
                    <p><strong>Марка:</strong> {{ addd.brand }}</p>
                    <p><strong>Модель:</strong> {{ addd.model }}</p>
                    <p><strong>Год выпуска:</strong> {{ addd.year }}</p>
                    <p><strong>Цена:</strong> {{ addd.price }} ₽</p>
                    <p>{{ addd.created_at }}</p>
                </div>
            {% endfor %}
        </div>
        
        <div class="pagination">
            <div class="step-links">
                <form method="get" >
                    {% if page_obj.has_previous %}
                        <button type="submit" name="page" value="1">&laquo; Первая</button>
                        <button type="submit" name="page" value="{{ page_obj.previous_page_number }}">Предыдущая</button>
                    {% endif %}
                    <span class="current">
                        Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}
                    </span>
                    {% if page_obj.has_next %}
                        <button type="submit" name="page" value="{{ page_obj.next_page_number }}">Следующая</button>
                        <button type="submit" name="page" value="{{ page_obj.paginator.num_pages }}">Последняя &raquo;</button>
                    {% endif %}
                </form>
            </div>
        </div>
    {% endif %}
{% endblock content %}

BboardSite/bboard/templates/bboard/user_addd.html
{% extends 'bboard/base.html' %}
{% load static %}


{% block content %}
{% if user == request.user%}
    <h2>Мои объявления</h2>
{% else %}
    <h2>Объяевления пользователя {{user.username}}</h2>
{% endif%}
<div class="post-list">
    {% for addd in addds %}
        <div class="post-item">
            <div>
                <h3><b>{{ addd.author }}</b></h3>
            </div>
            {% if post.image %}
                <img src="{{post.image.url}}" width="150px" height="auto">
            {% else %}
                <img src="{% static 'img/no_image.jpg' %}" width="150px" height="auto">
            {% endif %}
            <h4><a href="{{addd.get_absolute_url}}">{{ addd.title }}</a></h4>
            <p>{{ addd.text }}</p>
            <p>{{ addd.created_at }}</p>
        </div>
    {% endfor %}
</div>
{% endblock content %}

BboardSite/bboard/templates/bboard/user_info.html
{% extends 'bboard/base.html' %}

{% block content %}
<h3>Информация о пользователе</h3>
<div>Логин - {{user.username}}</div>
<div>Имя - {{user.first_name}}</div>
<div>Фамилия - {{user.last_name}}</div>
<div>Электронная почта - {{user.email}}</div>
<div>Дата регистрации: {{user.date_joined}}</div>

{% endblock content %}